let i18n = new Map([
    [
        'zh-CN', new Map([
            /* UI text */
            ['Send', '发送'],
            ['Settings', '设置'],
            ['Pin sidebar', '固定侧边栏'],
            ['Sound notifications', '提示音'],
            ['Screen notifications', '浏览器通知'],
            ['Join/left notify', '显示加入、退出消息'],
            ['Allow LaTeX', '显示LaTeX公式'],
            ['Allow Highlight', '代码高亮'],
            ['Allow Images', '显示图片'],
            ['Allow All Images (Not Recommended)', '允许所有来源的图片（不推荐）'],
            ['Soft @Mention', '@中间加空格'],
            ['Record Messages', '客户端记录信息'],
            ['Mobile buttons', '手机版按钮'],
            ['Index Online Count', '首页显示在线人数'],
            ['Language', '语言'],
            ['Color scheme', '配色方案'],
            ['Highlight scheme', '代码高亮方案'],
            ['Upload Image', '上传图片'],
            ['Clear all messages', '清空本页聊天记录'],
            ['Set auto color', '设置用户名自动改色'],
            ['Set Massage Template', '设置消息模板'],
            ['Copy JSON Record', '复制JSON记录'],
            ['Copy Message Record', '复制消息记录'],
            ['Don\'t Click', '隐藏功能'],
            ['Users online', '在线列表'],
            ['(Click user to invite; rightclick to ignore.)', '(点击邀请,右键拉黑)'],

            /* Alerts and prompts */
            ['Nickname:', '请输入用户名：'],
            ['Your nickname color:(press enter without inputing to reset; input "random" to set it to random)', '你的用户名颜色：（直接按回车重置，输入“random”设为随机。）'],
            ['target channel:(defaultly random channel generated by server)', '你要邀请对方到的频道名称：（默认为随机频道）'],
            ['', ''],
            ['', ''],
            ['', ''],
            ['', ''],
            ['', ''],
            ['', ''],
            ['', ''],
            ['', ''],

            /* System messages */
            ['Users online: ', '在线用户'],
            ['Thanks for using hackchat++ client! Source at: ', '感谢使用hackchat++！开源在：'],
            [/^([a-zA-Z0-9_]{1,24}) joined/, '$1 加入了聊天室'],
            [/^([a-zA-Z0-9_]{1,24}) left/, '$1 离开了聊天室'],
            ['You cancelled joining. Press enter at the input field to reconnect.', '你取消了加入。在输入框上按回车可以重新加入。'],
            ['Server disconnected. Attempting to reconnect. . .', '断连了！正在尝试重连……'],
            ['Failed to connect to server. When you think there is chance to succeed in reconnecting, press enter at the input field to reconnect.', '连接到服务器失败。如果你想重连，在输入框上按回车即可。'],
            [/You may be kicked or moved to this channel by force to channel \?(.+) \. Unable to get full user list\. /, '你可能被踢到或者强制移到了频道 ?$1 。无法获取完整用户列表。'],
            [/Unexpected Channel \?(.+) \. You may be kicked or moved to this channel by force\. /, '异常：你现在在频道 ?$1 。你可能被踢出了，或者被强制移动了。'],
            [/Unexpected Channel \?(.+) \. You may be locked out from \?(.+) \. You may also be kicked or moved to this channel by force\. /, '异常：你现在在频道 ?$1 。可能是 ?$2 锁房了，把你屏蔽在了 ?$1 。也可能是你被踢出了，或者被强制移动了。'],
            [/You are now at \?(.+) \. A mod has moved you、. /, '你现在在 ?$1 了。一名管理员移动了你。'],
            ['Please refresh to apply language. Multi language is in test and not perfect yet. ', '请刷新来应用语言设置。多语言支持目前还在测试当中，并不完美。'],

            /* Chatroom info */
            [/You whispered to @([a-zA-Z0-9_]{1,24}): /, '你对 @$1 私聊：'],
            [/([a-zA-Z0-9_]{1,24}) whispered: /, '$1 对你私聊：'],
            [/You invited ([a-zA-Z0-9_]{1,24}) to /, '你邀请 $1 到 '],
            [/([a-zA-Z0-9_]{1,24}) invited you to /, '$1 邀请你到 '],
            ['Nickname must consist of up to 24 letters, numbers, and underscores', '用户名只能包含24个及以下字符，只能包含字母、数字和下划线'],
            ['Nickname taken', '该用户名已被占用'],
            ['You have been denied access to that channel and have been moved somewhere else. Retry later or wait for a mod to move you.', '系统阻止了你加入该频道，把你移到了别的地方。请稍后尝试或等待管理员移动你。'],
            ['Enter the following to join (case-sensitive):', '请输入以下验证码：（大小写敏感）'],
            ['You are joining channels too fast. Wait a moment and try again.', '你加入得太快了，请稍后重试。'],
            ['You are sending too much text. Wait a moment and try again.\nPress the up arrow key to restore your last message.', '你发送了太多消息。请稍后重试。按方向上键来恢复没发出去的消息。'],
            ['You are being rate-limited or blocked.', '你被暂时限制了，或者被封禁了。'],

            /* Frontpage text */
            ['Welcome to hack.chat, a minimal, distraction-free chat application.', '欢迎来到hack.chat，最小化、无干扰的聊天室。'],
            ['You are now experiencing hack.chat with a tweaked client: hackchat\\+\\+. Official hack.chat client is at: https://hack.chat.', '你正在使用一个改版客户端，hackchat++，体验 hack.chat。官方客户端在此：https://hack.chat。'],
            ['Channels are created, joined and shared with the url, create your own channel by changing the text after the question mark. Example: ', '频道是通过网址创建、加入和分享的。通过改变问号后的内容，你就可以创建自己的频道。例如：'],
            ['There are no channel lists *for normal users*, so a secret channel name can be used for private discussions.', '没有*公开给普通人*的频道列表，所以一个秘密的频道名称可以用于私密交流。'],
            ['Here are some pre-made channels you can join: ', '以下是一些你可以加入的公开频道：'],
            ['(Online counts disabled)', '（在线人数显示已关闭）'],
            ['(Getting online counts...)', '（正在获取在线人数……）'],
            [/\((\d+) users online, /, '（当你进入这个首页时，全站在线用户数为$1，'],
            [/(\d+) channels existing when you enter this page\)/, '全站频道数为$1）'],
            ['And here\'s a random one generated just for you: ', '这是一个为你准备的随机频道：'],
            ['Formatting:', '排版：'],
            ['Notice: Dont send raw source code without using a code block!', '注意：不要不带代码块直接发源代码！'],
            ['Surround LaTeX with a dollar sign for inline style $\\zeta(2) = \\pi^2/6$, and two dollars for display. ', '用美元符号包裹行内公式： $\\zeta(2) = \\pi^2/6$，用两个美元符号包裹块级公式。'],
            ['For syntax highlight, wrap the code like: \\`\\`\\`<language> <the code>\\`\\`\\` where <language> is any known programming language.', '像这样包裹代码来获得语法高亮：\\`\\`\\`<编程语言名称> <代码>\\`\\`\\`'],
            ['Current Github: ', '当前Github仓库：'],
            ['Legacy GitHub: ', '旧版Github仓库：'],
            ['Bots, Android clients, desktop clients, browser extensions, docker images, programming libraries, server modules and more:', '机器人，安卓客户端，桌面客户端，浏览器扩展，Docker映像，编程库，服务端模块和更多：'],
            ['Server and web client released under the WTFPL and MIT open source license.', '服务端和网页客户端分别采用WTFPL和MIT协议开源。'],
            ['No message history is retained on the hack.chat server, but in certain channels there may be bots made by users which record messages.', '没有聊天记录保存在hack.chat服务器上，但是在某些频道，可能有用户做的机器人保存聊天记录。'],
            ['Github of hackchat++ (aka hackchat-client-plus)', 'hackchat++（又名hackchat client plus）的Github：'],
            ['Hosted at https://hcer.netlify.app/ and hc.thz.cool(thanks to Maggie, aka THZ, for hosting).', '托管在 https://hcer.netlify.app/ 和 hc.thz.cool（感谢Maggie，即THZ，提供托管）。'],
            ['Links: ', '友情链接：'],
            [' (Thanks for providing replying script!) ', '（感谢提供回复功能的代码）']
        ])
    ]
])

function i18ntranslate(text) {
    if (lang == 'en-US' || !i18n.has(lang)) return text
    for (let item of i18n.get(lang)) {
        text = text.replace(item[0], item[1])
    }
    return text
}

function localStorageGet(key) {
    try {
        return window.localStorage[key]
    } catch (e) { }
}

let lang = 'en-US'

if (localStorageGet('i18n') && localStorageGet('i18n') != 'en-US') {
    if (i18n.has(localStorageGet('i18n'))) {
        document.querySelector('html').lang = lang
        lang = localStorageGet('i18n')
        document.querySelectorAll('[tr]').forEach((el) => {
            el.innerHTML = i18ntranslate(el.innerHTML)
        })
    } else {
        alert(`Sorry, we have not made language ${localStorageGet('i18n')}. You can try: zh-CN.`)
    }
}